### ISSUE TITLE
By changing the font-size to a bigger one sroll-bars start to pop up

### ISSUE THREAD

**Issue by guserav** [guserav/WebEngiMitLenni#17]

**Comment by Oswaldbob** [comment]
most likely not fixable due to min lenghts etc
Could be an enhancement :)

**Comment by guserav** [comment]
why do they have min lengths in the first place?

**Comment by Oswaldbob** [comment]
if you would have a huge div to scroll your scrollbar would adatpe to the lenght and would not be bigger than a pixel

**Comment by Oswaldbob** [comment]
Nevermind I missunderstood your question. 

Will look into the problem. But the reason is that the min lenght of our divs (chat log and side menu and topbar) are not allowed to be smaller than a certain amount. if we would understep the amount you would not be able to read or see objects in the div anymore

**Comment by Oswaldbob** [comment]
Fixed with commit, topbar container did not have a height.
